@extends('layouts.admin')
@section('title', 'Site settings')
@section('content')
<div class="page-heading"><div><p class="eyebrow">BUSINESS PROFILE</p><h1>Site settings</h1><p class="muted">Manage the brand, contact details, location, business information, and social profiles used across the website.</p></div><a class="button button-outline" href="{{ route('contact') }}" target="_blank" rel="noopener">View contact page ↗</a></div>
<form method="post" action="{{ route('admin.settings.update') }}" enctype="multipart/form-data" class="stack about-editor">@csrf @method('PUT')
<section class="panel form-panel"><div><p class="eyebrow">BRAND</p><h2>Business identity</h2><p class="muted">These details appear in the website header, footer, browser metadata, and contact page.</p></div><div class="form-columns"><label>Website name<input name="site_name" value="{{ old('site_name', $settings['site_name']) }}" maxlength="150" required></label><label>Legal business name<input name="legal_name" value="{{ old('legal_name', $settings['legal_name']) }}" maxlength="200"></label></div><label>Tagline<input name="tagline" value="{{ old('tagline', $settings['tagline']) }}" maxlength="255"></label><label>Business description<textarea name="business_description" rows="4" maxlength="1000">{{ old('business_description', $settings['business_description']) }}</textarea><small>Shown in the footer and used as a concise public introduction.</small></label><label>Default search description<textarea name="default_meta_description" rows="3" maxlength="500">{{ old('default_meta_description', $settings['default_meta_description']) }}</textarea><small>Used by pages that do not provide their own search description.</small></label></section>
<section class="panel form-panel"><div><p class="eyebrow">LOGO</p><h2>Website logo</h2><p class="muted">Upload a transparent PNG or WebP when possible. The existing logo remains until you replace or remove it.</p></div><div class="image-picker" data-image-picker><span class="image-picker-label">Header and footer logo</span><div class="image-picker-body"><img class="image-picker-preview" data-image-preview src="{{ $settings['logo_path'] ? asset('storage/'.$settings['logo_path']) : asset('assets/images/logo.png') }}" alt="Current website logo"><div class="image-picker-controls"><label>Choose logo from device<input type="file" name="logo" accept="image/jpeg,image/png,image/webp" data-image-input><small>JPG, PNG, or WebP. Maximum 2 MB and 6000 × 6000 pixels.</small></label><p class="image-picker-feedback muted" data-image-feedback aria-live="polite"></p>@if($settings['logo_path'])<label class="checkbox"><input type="hidden" name="remove_logo" value="0"><input type="checkbox" name="remove_logo" value="1"> Remove uploaded logo and use the original</label>@endif</div></div></div><label>Logo description<input name="logo_alt" value="{{ old('logo_alt', $settings['logo_alt']) }}" maxlength="255" placeholder="Business name"></label></section>
<section class="panel form-panel"><div><p class="eyebrow">CONTACT</p><h2>Email, phone, and messaging</h2></div><div class="form-columns"><label>Public contact email<input type="email" name="contact_email" value="{{ old('contact_email', $settings['contact_email']) }}" maxlength="255" required></label><label>Enquiry recipient email<input type="email" name="enquiry_email" value="{{ old('enquiry_email', $settings['enquiry_email']) }}" maxlength="255"><small>Contact-form messages go here. Leave empty to use the public email.</small></label></div><div class="form-columns"><label>Primary phone<input name="contact_phone" value="{{ old('contact_phone', $settings['contact_phone']) }}" maxlength="50"></label><label>Alternate phone<input name="alternate_phone" value="{{ old('alternate_phone', $settings['alternate_phone']) }}" maxlength="50"></label></div><label>WhatsApp number<input name="whatsapp_phone" value="{{ old('whatsapp_phone', $settings['whatsapp_phone']) }}" maxlength="50" placeholder="+977 9800000000"><small>Include the country code. The contact page creates the WhatsApp link automatically.</small></label></section>
<section class="panel form-panel"><div><p class="eyebrow">LOCATION</p><h2>Address and map</h2></div><label>Street address<textarea name="address" rows="3" maxlength="500">{{ old('address', $settings['address']) }}</textarea></label><div class="form-columns"><label>City<input name="city" value="{{ old('city', $settings['city']) }}" maxlength="100"></label><label>Postal code<input name="postal_code" value="{{ old('postal_code', $settings['postal_code']) }}" maxlength="30"></label></div><label>Country<input name="country" value="{{ old('country', $settings['country']) }}" maxlength="100"></label><label>Map embed URL<input type="url" name="map_embed_url" value="{{ old('map_embed_url', $settings['map_embed_url']) }}" maxlength="2000"><small>Paste an HTTPS Google Maps embed URL or OpenStreetMap embed URL.</small></label><label>Directions URL<input type="url" name="map_directions_url" value="{{ old('map_directions_url', $settings['map_directions_url']) }}" maxlength="1000"><small>Used by the “Get directions” link on the contact page.</small></label></section>
<section class="panel form-panel"><div><p class="eyebrow">BUSINESS DETAILS</p><h2>Hours and registration</h2></div><label>Business hours<textarea name="business_hours" rows="4" maxlength="1000" placeholder="Sunday–Friday: 9:00 AM–6:00 PM&#10;Saturday: By appointment">{{ old('business_hours', $settings['business_hours']) }}</textarea><small>Enter one schedule per line.</small></label><div class="form-columns"><label>Response-time message<input name="response_time" value="{{ old('response_time', $settings['response_time']) }}" maxlength="255"></label><label>Registration number<input name="registration_number" value="{{ old('registration_number', $settings['registration_number']) }}" maxlength="100"></label></div></section>
<section class="panel form-panel"><div><p class="eyebrow">SOCIAL MEDIA</p><h2>Public profile links</h2><p class="muted">Only completed links appear on the website.</p></div><div class="form-columns"><label>Facebook URL<input type="url" name="facebook_url" value="{{ old('facebook_url', $settings['facebook_url']) }}" maxlength="500" placeholder="https://facebook.com/..."></label><label>Instagram URL<input type="url" name="instagram_url" value="{{ old('instagram_url', $settings['instagram_url']) }}" maxlength="500" placeholder="https://instagram.com/..."></label></div><div class="form-columns"><label>YouTube URL<input type="url" name="youtube_url" value="{{ old('youtube_url', $settings['youtube_url']) }}" maxlength="500" placeholder="https://youtube.com/..."></label><label>LinkedIn URL<input type="url" name="linkedin_url" value="{{ old('linkedin_url', $settings['linkedin_url']) }}" maxlength="500" placeholder="https://linkedin.com/..."></label></div></section>
<div class="about-save-bar"><p class="muted">Saving updates the public header, footer, contact page, map, and enquiry delivery settings.</p><div class="about-save-actions"><a class="button button-outline" href="{{ route('admin.dashboard') }}">Cancel</a><button class="button" type="submit">Save site settings →</button></div></div>
</form>
@endsection
