<?php
require __DIR__ . '/includes/site.php';
render_header('About Ayurveda', 'Explore the timeless principles of Ayurveda and how they support balance, prevention, healing, and long-term wellbeing.');
render_hero('Ancient wisdom for modern life', 'Discover the timeless healing wisdom of Ayurveda at Takshasheela.', 'A time-tested healing science focused on restoring balance between body, mind, and spirit.', 'hero--water');
?>
<section class="section section--cream"><div class="shell split"><div class="split__media" data-reveal><img src="assets/images/inclusivity.jpg" alt="A calm natural setting for Ayurvedic care" loading="lazy"></div><div class="split__content" data-reveal><p class="eyebrow">Ancient wisdom for modern life</p><h2>What is Ayurveda?</h2><p>Ayurveda is a time-tested healing science from India that focuses on restoring balance between the body, mind, and spirit. At Takshasheela Ayurveda Aashram, we use this sacred knowledge to guide guests towards natural harmony, vitality, and inner peace.</p><p>Through personalised care, nourishing food, herbal support, mindful movement, and restorative therapies, Ayurveda helps create lasting wellbeing rather than temporary relief.</p></div></div></section>
<section class="section dosha-section"><div class="shell"><div class="section-heading section-heading--center" data-reveal><p class="eyebrow">The three doshas</p><h2>Three energies shape our individual nature.</h2><p class="lede">Ayurveda describes Vata, Pitta, and Kapha as patterns formed by the five elements. Everyone carries all three in a unique proportion.</p></div><div class="card-grid">
<article class="feature-card dosha-card" data-reveal><img src="assets/images/dosha-vata.webp" alt="Airy grasses and flowing fabric representing Vata dosha" loading="lazy" width="960" height="720"><div class="feature-card__body"><p class="eyebrow">Air + Space</p><h3>Vata</h3><p>Vata represents movement, creativity, and adaptability. When balanced, it supports lightness and clear expression; steady routines, warmth, and rest help calm its changeable qualities.</p></div></article>
<article class="feature-card dosha-card" data-reveal><img src="assets/images/dosha-pitta.webp" alt="Warm copper, water, and botanicals representing Pitta dosha" loading="lazy" width="960" height="720"><div class="feature-card__body"><p class="eyebrow">Fire + Water</p><h3>Pitta</h3><p>Pitta represents transformation, digestion, focus, and discernment. When balanced, it supports clarity and purpose; cooling foods, moderation, and spaciousness soften its intensity.</p></div></article>
<article class="feature-card dosha-card" data-reveal><img src="assets/images/dosha-kapha.webp" alt="Earth, water, stones, and green leaves representing Kapha dosha" loading="lazy" width="960" height="720"><div class="feature-card__body"><p class="eyebrow">Earth + Water</p><h3>Kapha</h3><p>Kapha represents structure, nourishment, steadiness, and endurance. When balanced, it brings calm and resilience; movement, variety, and lightness help enliven its grounded nature.</p></div></article>
</div></div></section>
<?php render_cta('Curious about Ayurveda?', 'Speak with our team about how personalised Ayurvedic care may support you.'); render_footer(); ?>
