<?php
require __DIR__ . '/includes/site.php';
render_header('Accommodations', 'Explore comfortable, peaceful rooms designed to support rest and rejuvenation during your Takshasheela stay.');
render_hero('Accommodations', 'Stay in comfort and tranquillity.', 'Explore a variety of thoughtfully designed accommodations tailored to provide comfort, tranquillity, and a deep connection with nature.', 'hero--stay');
?>
<section class="section"><div class="shell intro-grid" data-reveal><div><p class="eyebrow">Our Rooms &amp; Suites</p><h2>Discover Your Perfect Stay</h2></div><div class="intro-copy"><p>Each room at Takshasheela is thoughtfully arranged to support rest, comfort, and renewal throughout your retreat experience.</p></div></div></section>
<section class="section section--cream"><div class="shell split"><div class="split__media split__media--landscape" data-reveal><img src="assets/images/standard-room.jpg" alt="Standard room at Takshasheela" loading="lazy"></div><div class="split__content" data-reveal><p class="eyebrow">Standard Room</p><h2>Comfortable and peaceful.</h2><p>Our Standard Rooms offer a cozy and peaceful environment, ideal for guests seeking simplicity, comfort, and a restful stay during their wellness journey.</p><a class="text-link" href="contact.php">Check availability</a></div></div></section>
<section class="section"><div class="shell split split--reverse"><div class="split__media split__media--landscape" data-reveal><img src="assets/images/deluxe-room.jpg" alt="Deluxe room at Takshasheela" loading="lazy"></div><div class="split__content" data-reveal><p class="eyebrow">Deluxe Room</p><h2>Elevated comfort and space.</h2><p>Experience elevated comfort in our Deluxe Rooms, featuring spacious interiors and a serene atmosphere designed to support deep rest and renewal.</p><a class="text-link" href="contact.php">Check availability</a></div></div></section>
<?php render_cta('Plan your stay', 'Ask about room availability, retreat dates, and room features.'); render_footer(); ?>
