@extends('layouts.site')
@section('title', $offering->name)
@section('description', $offering->short_description)
@section('theme', 'detail')
@section('content')
<section class="offering-detail section"><div class="shell offering-detail__grid"><div class="offering-detail__media" data-reveal><img src="{{ $offering->imageUrl() }}" alt="{{ $offering->image_alt }}"></div><div class="offering-detail__content" data-reveal><nav class="breadcrumb" aria-label="Breadcrumb"><a href="{{ route('home') }}">Home</a><span>/</span><a href="{{ $category->publicUrl() }}">{{ $category->name }}</a>@if($offering->subcategory)<span>/</span><a href="{{ $category->publicUrl() }}#{{ $offering->subcategory->slug }}">{{ $offering->subcategory->name }}</a>@endif<span>/</span><span>{{ $offering->name }}</span></nav><p class="eyebrow">{{ $offering->eyebrow }}</p><h1>{{ $offering->name }}</h1>@if($offering->duration)<p class="offering-detail__meta">Duration <strong>{{ $offering->duration }}</strong></p>@endif<div class="offering-detail__descriptions">@if($offering->subcategory?->description)<section class="offering-detail__description"><p class="eyebrow">{{ $offering->subcategory->name }}</p><x-rich-text :content="$offering->subcategory->description" /></section>@endif<section class="offering-detail__description"><p class="eyebrow">{{ $offering->name }}</p><x-rich-text :content="$offering->description" /></section></div><a class="button" href="{{ route('contact', ['interest' => $offering->name]) }}">Enquire about this program</a><div class="offering-facts"><details open><summary>What is included</summary><ul>@foreach($offering->includes as $included)<li>{{ $included }}</li>@endforeach</ul></details>@if($offering->itinerary)<details><summary>Itinerary</summary><ol class="itinerary-list">@foreach($offering->itinerary as $stop)<li><span>{{ $stop['time'] }}</span><div><strong>{{ $stop['title'] }}</strong><p>{{ $stop['description'] }}</p></div></li>@endforeach</ol></details>@endif<details><summary>Who it may suit</summary><x-rich-text :content="$offering->ideal_for" /></details><details><summary>{{ $offering->secondary_title }}</summary><x-rich-text :content="$offering->secondary_content" /></details></div>@if($offering->notice)<x-rich-text class="offering-note" :content="$offering->notice" />@endif</div></div></section>
@include('site.partials.video')
@if($related->isNotEmpty())<section class="section section--cream"><div class="shell"><div class="section-heading"><p class="eyebrow">Other {{ strtolower($category->name) }}</p><h2>Explore another path.</h2></div><div class="card-grid">@foreach($related as $item)<article class="feature-card"><img src="{{ $item->imageUrl() }}" alt="{{ $item->image_alt }}" loading="lazy"><div class="feature-card__body"><p class="eyebrow">{{ $item->eyebrow }}</p><h3>{{ $item->name }}</h3><p>{{ $item->short_description }}</p><a class="text-link" href="{{ $item->publicUrl() }}">View details</a></div></article>@endforeach</div></div></section>@endif
@include('site.partials.cta', ['eyebrow' => $category->cta_eyebrow, 'heading' => $category->cta_title, 'copy' => $category->cta_body])
@endsection
