@extends('layouts.admin')
@section('title', 'Homepage')
@section('content')
<div class="page-heading"><div><p class="eyebrow">PUBLIC WEBSITE</p><h1>Homepage</h1><p class="muted">Manage the homepage hero and philosophy quote. The Inclusivity section comes directly from About Takshasheela.</p></div><a class="button button-outline" href="{{ route('home') }}" target="_blank" rel="noopener">View homepage ↗</a></div>
<form method="post" action="{{ route('admin.home.update') }}" enctype="multipart/form-data" class="stack about-editor">@csrf @method('PUT')
<section class="panel form-panel"><div><p class="eyebrow">HERO</p><h2>Opening section</h2><p class="muted">Update the homepage introduction and its background media.</p></div>
<div class="form-columns"><label>Eyebrow<input name="hero[eyebrow]" value="{{ old('hero.eyebrow', $heroSection->content['eyebrow']) }}" maxlength="150"></label><label>Main heading<input name="hero[title]" value="{{ old('hero.title', $heroSection->content['title']) }}" maxlength="255" required></label></div>
<label>Description<textarea data-wysiwyg name="hero[description]" rows="3" maxlength="1000">{{ old('hero.description', $heroSection->content['description']) }}</textarea></label>
<div class="form-columns"><label>Location / scroll note<input name="hero[scroll_note]" value="{{ old('hero.scroll_note', $heroSection->content['scroll_note']) }}" maxlength="150"></label><label>Poster image description<input name="hero[poster_alt]" value="{{ old('hero.poster_alt', $heroSection->content['poster_alt']) }}" maxlength="255"></label></div>
<div class="image-picker" data-image-picker><span class="image-picker-label">Hero poster image</span><div class="image-picker-body"><img class="image-picker-preview" data-image-preview @if($heroSection->mediaUrl('poster_path')) src="{{ $heroSection->mediaUrl('poster_path') }}" @else hidden @endif alt="Current hero poster"><div class="image-picker-controls"><label>Choose poster from device<input type="file" name="poster" accept="image/jpeg,image/png,image/webp" data-image-input><small>JPG, PNG, or WebP. Maximum 2 MB.</small></label><p class="image-picker-feedback muted" data-image-feedback aria-live="polite"></p>@if($heroSection->content['poster_path'] ?? null)<label class="checkbox"><input type="checkbox" name="remove_poster" value="1" data-image-remove> Remove current poster</label>@endif</div></div></div>
<div class="home-video-picker"><span class="image-picker-label">Hero background video</span>@if($heroSection->mediaUrl('video_path'))<video controls muted preload="metadata" poster="{{ $heroSection->mediaUrl('poster_path') }}"><source src="{{ $heroSection->mediaUrl('video_path') }}"></video>@endif<label>Choose video from device<input type="file" name="video" accept="video/mp4,video/webm"><small>MP4 or WebM, maximum 80 MB. Your server upload limit must allow the selected file.</small></label>@if($heroSection->content['video_path'] ?? null)<label class="checkbox"><input type="checkbox" name="remove_video" value="1"> Remove current video and show only the poster</label>@endif</div>
</section>
<section class="panel form-panel"><div><p class="eyebrow">PHILOSOPHY</p><h2>Homepage quotation</h2></div><label>Quote<textarea name="philosophy[quote]" rows="4" maxlength="1000" required>{{ old('philosophy.quote', $philosophySection->content['quote']) }}</textarea></label><label>Attribution<input name="philosophy[attribution]" value="{{ old('philosophy.attribution', $philosophySection->content['attribution']) }}" maxlength="255"></label></section>
<section class="panel form-panel"><div><p class="eyebrow">ABOUT / INCLUSIVITY</p><h2>Shared from About Takshasheela</h2><p class="muted">The homepage uses the first Inclusivity content block from About Takshasheela, including its image and description.</p></div><a class="button button-outline" href="{{ route('admin.about.edit', 'about-takshasheela') }}">Edit Inclusivity content →</a></section>
<div class="about-save-bar"><p class="muted">Saving updates the public homepage immediately.</p><div class="about-save-actions"><button class="button" type="submit">Save homepage →</button></div></div>
</form>
@endsection
