@extends('layouts.admin')
@php($editing = $subcategory->exists)
@section('title', $editing ? 'Edit '.$subcategory->name : 'Add wellness subcategory')
@section('content')
<div class="page-heading"><div><p class="eyebrow">WELLNESS SUBCATEGORY</p><h1>{{ $editing ? 'Edit '.$subcategory->name : 'Add subcategory' }}</h1><p class="muted">Creates the middle level between a top-level category and its offerings.</p></div><a class="button button-outline" href="{{ route('admin.wellness-subcategories.index') }}">← All subcategories</a></div>
@if($categories->isEmpty())
<section class="panel empty-state"><span class="empty-icon">◇</span><h3>Create a category first</h3><p>Every subcategory must belong to a top-level category.</p><a class="button" href="{{ route('admin.wellness-categories.create') }}">Add category</a></section>
@else
<form method="post" action="{{ $editing ? route('admin.wellness-subcategories.update', $subcategory) : route('admin.wellness-subcategories.store') }}" class="stack about-editor">@csrf @if($editing) @method('PUT') @endif
<section class="panel form-panel"><div><p class="eyebrow">HIERARCHY</p><h2>Subcategory details</h2></div><label>Parent category<select name="wellness_category_id" required>@foreach($categories as $category)<option value="{{ $category->id }}" @selected((int) old('wellness_category_id', $subcategory->wellness_category_id) === $category->id)>{{ $category->name }}</option>@endforeach</select></label><label>Subcategory name<input name="name" value="{{ old('name', $subcategory->name) }}" maxlength="140" required><small>The slug is generated automatically. Moving it to another category creates an available slug there.</small></label><label>Menu description<input name="nav_description" value="{{ old('nav_description', $subcategory->nav_description) }}" maxlength="255" placeholder="Short description shown in the website menu"><small>Keep this concise for navigation and listing headings.</small></label><label>Full description<textarea data-wysiwyg name="description" rows="7" maxlength="20000" placeholder="Describe this subcategory in detail">{{ old('description', $subcategory->description) }}</textarea><small>Shown first on every offering detail page in this subcategory. Use the toolbar to format this content.</small></label></section>
<section class="panel form-panel"><div><p class="eyebrow">VISIBILITY</p><h2>Publishing and order</h2></div><div class="form-columns"><label>Display order<input type="number" name="sort_order" value="{{ old('sort_order', $subcategory->sort_order) }}" min="0" max="9999" required><small>Lower numbers appear first within the parent category.</small></label><label class="checkbox accommodation-publish"><input type="hidden" name="is_published" value="0"><input type="checkbox" name="is_published" value="1" @checked(old('is_published', $subcategory->is_published))> Published on the website</label></div></section>
<div class="about-save-bar"><p class="muted">Published subcategories group offerings in the website menu and listing page.</p><div class="about-save-actions"><a class="button button-outline" href="{{ route('admin.wellness-subcategories.index') }}">Cancel</a><button class="button" type="submit">{{ $editing ? 'Save subcategory' : 'Create subcategory' }} →</button></div></div>
</form>
@endif
@endsection
