@extends('layouts.site')
@section('title', $accommodation->name)
@section('description', $accommodation->short_description)
@section('theme', 'detail')
@section('content')
<section class="offering-detail section"><div class="shell offering-detail__grid"><div class="offering-detail__media" data-reveal><img src="{{ $accommodation->imageUrl() }}" alt="{{ $accommodation->image_alt }}"></div><div class="offering-detail__content" data-reveal><nav class="breadcrumb" aria-label="Breadcrumb"><a href="{{ route('home') }}">Home</a><span>/</span><a href="{{ route('accommodations.index') }}">Accommodations</a><span>/</span><span>{{ $accommodation->name }}</span></nav><p class="eyebrow">{{ $accommodation->category }}</p><h1>{{ $accommodation->name }}</h1><x-rich-text class="offering-detail__lead" :content="$accommodation->description" /><a class="button" href="{{ route('contact', ['interest' => $accommodation->name]) }}">Check availability</a><div class="offering-facts"><details open><summary>Room features</summary><ul>@foreach($accommodation->features as $feature)<li>{{ $feature }}</li>@endforeach</ul></details><details><summary>Who it may suit</summary><x-rich-text :content="$accommodation->ideal_for" /></details><details><summary>Before you book</summary><x-rich-text :content="$accommodation->stay_note" /></details></div><p class="offering-note">Accommodation availability depends on your retreat dates. Our team will confirm the room arrangement and what is included with your stay.</p></div></div></section>
@if($related->isNotEmpty())<section class="section section--cream"><div class="shell"><div class="section-heading"><p class="eyebrow">Another option</p><h2>Explore our rooms.</h2></div><div class="card-grid card-grid--compact">@foreach($related as $room)<article class="feature-card"><img src="{{ $room->imageUrl() }}" alt="{{ $room->image_alt }}" loading="lazy"><div class="feature-card__body"><p class="eyebrow">{{ $room->category }}</p><h3>{{ $room->name }}</h3><p>{{ $room->short_description }}</p><a class="text-link" href="{{ route('accommodations.show', $room->slug) }}">View accommodation</a></div></article>@endforeach</div></div></section>@endif
@include('site.partials.cta', ['eyebrow' => 'Plan your stay', 'heading' => 'Ask about availability, retreat dates, and the room setup you need.'])
@endsection
