@extends('layouts.site')
@section('title', 'Ayurvedic healing and restorative stays')
@section('description', $siteSettings['default_meta_description'])
@section('theme', 'dark')
@section('content')
@php
    $mediaUrl = fn (?string $path) => ! $path ? null : (str_starts_with($path, 'assets/') ? asset($path) : asset('storage/'.$path));
    $heroPoster = $mediaUrl($hero['poster_path'] ?? null);
    $heroVideo = $mediaUrl($hero['video_path'] ?? null);
    $aboutImage = $mediaUrl($aboutIntro['image'] ?? null);
@endphp
<section class="home-hero" @if($heroPoster) style="background-image:url('{{ $heroPoster }}')" @endif>
    @if($heroVideo)<video class="home-hero__video" autoplay muted loop playsinline preload="metadata" @if($heroPoster) poster="{{ $heroPoster }}" @endif aria-label="{{ $hero['poster_alt'] ?? '' }}" data-hero-video><source src="{{ $heroVideo }}"></video>@endif
    <div class="shell home-hero__content" data-reveal><p class="eyebrow eyebrow--light">{{ $hero['eyebrow'] }}</p><h1>{{ $hero['title'] }}</h1><div class="home-hero__bottom"><x-rich-text class="home-hero__description" :content="$hero['description']" />@if($hero['scroll_note'])<span class="scroll-note">{{ $hero['scroll_note'] }}</span>@endif</div></div>
</section>
<section class="section section--cream home-about"><div class="shell split">@if($aboutImage)<div class="split__media" data-reveal><img src="{{ $aboutImage }}" alt="{{ $aboutIntro['image_alt'] ?? '' }}" loading="lazy"></div>@endif<div class="split__content" data-reveal><p class="eyebrow">{{ $aboutIntro['eyebrow'] ?? '' }}</p><h2>{{ $aboutIntro['title'] }}</h2><x-rich-text :content="$aboutIntro['body'] ?? ''" /><a class="button button--outline" href="{{ route('about') }}">Discover our story</a></div></div></section>
<section class="section"><div class="shell"><div class="home-products__heading" data-reveal><div><p class="eyebrow">Packages</p><h2>Our packages that heal the past and open the future.</h2></div><div><p>From focused therapies to immersive stays, every experience is grounded in individual assessment and gentle progression.</p><a class="text-link" href="{{ route('programs.index') }}">View all packages</a></div></div><div class="card-grid">
@forelse($packages as $program)<article class="feature-card" data-reveal><a href="{{ $program->publicUrl() }}"><img src="{{ $program->imageUrl() }}" alt="{{ $program->image_alt }}" loading="lazy"></a><div class="feature-card__body"><p class="eyebrow">{{ $program->eyebrow }}</p><h3><a class="card-title-link" href="{{ $program->publicUrl() }}">{{ $program->name }}</a></h3><p>{{ $program->short_description }}</p><a class="text-link" href="{{ $program->publicUrl() }}">View package details</a></div></article>@empty<p>No wellness packages are published yet.</p>@endforelse
</div></div></section>
<section class="section home-products"><div class="shell"><div class="home-products__heading" data-reveal><div><p class="eyebrow">From our apothecary</p><h2>Carry the ritual home.</h2></div><div><p>Botanical essentials inspired by the daily rhythms of {{ $siteSettings['site_name'] }}.</p><a class="text-link" href="{{ route('products.index') }}">Explore all products</a></div></div><div class="product-grid product-grid--home">
@forelse($products as $product)<article class="product-card" data-reveal><a class="product-card__image" href="{{ route('products.show', $product->slug) }}"><img src="{{ $product->imageUrl() }}" alt="{{ $product->image_alt }}" loading="lazy"></a><div class="product-card__body"><p class="product-card__meta">{{ $product->category }} · {{ $product->size }}</p><h3><a href="{{ route('products.show', $product->slug) }}">{{ $product->name }}</a></h3><p>{{ $product->short_description }}</p><div class="product-card__footer"><strong>{{ $product->price }}</strong><a class="text-link" href="{{ route('products.show', $product->slug) }}">View product</a></div></div></article>@empty<p>No products are published yet.</p>@endforelse
</div></div></section>
<section class="section section--cream"><div class="shell"><div class="home-products__heading" data-reveal><div><p class="eyebrow">Guest reflections</p><h2>What our clients say about us.</h2></div><div><p>Read how guests describe their experiences of rest, care, and renewal.</p><a class="text-link" href="{{ route('testimonials') }}">Read all guest reflections</a></div></div><div class="card-grid">
@forelse($testimonials as $testimonial)<article class="testimonial-card"><p class="testimonial-card__rating" aria-label="{{ $testimonial->rating }} out of five stars">{{ str_repeat('★', $testimonial->rating) }}</p><h3>{{ $testimonial->title }}</h3><blockquote>“{{ $testimonial->quote }}”</blockquote><footer><span>{{ $testimonial->initials() }}</span><p><strong>{{ $testimonial->guest_name }}</strong>{{ $testimonial->guest_location }}</p></footer></article>@empty<p>No guest reflections are published yet.</p>@endforelse
</div></div></section>
<section class="quote-section"><div class="shell" data-reveal><blockquote>“{{ $philosophy['quote'] }}”@if($philosophy['attribution'])<cite>{{ $philosophy['attribution'] }}</cite>@endif</blockquote></div></section>
@foreach([['items' => $blogs, 'eyebrow' => 'Blogs', 'heading' => 'Staying inspired & connected.', 'copy' => 'Ideas, reflections, and practical wisdom for a more conscious approach to everyday wellbeing.', 'route' => 'blogs.index'], ['items' => $news, 'eyebrow' => 'News & Events', 'heading' => 'What is unfolding at '.$siteSettings['site_name'].'.', 'copy' => 'Retreat dates, community gatherings, and seasonal moments from the Aashram.', 'route' => 'news.index']] as $section)
<section class="section {{ $loop->first ? 'section--cream' : '' }}"><div class="shell"><div class="home-products__heading" data-reveal><div><p class="eyebrow">{{ $section['eyebrow'] }}</p><h2>{{ $section['heading'] }}</h2></div><div><p>{{ $section['copy'] }}</p><a class="text-link" href="{{ route($section['route']) }}">Explore all {{ strtolower($section['eyebrow']) }}</a></div></div><div class="card-grid">@forelse($section['items'] as $article)<article class="feature-card" data-reveal><a href="{{ route('chronicles.show', $article->slug) }}"><img src="{{ $article->imageUrl() }}" alt="{{ $article->image_alt }}" loading="lazy"></a><div class="feature-card__body"><p class="eyebrow">{{ $article->category }}</p><h3><a class="card-title-link" href="{{ route('chronicles.show', $article->slug) }}">{{ $article->title }}</a></h3><p>{{ $article->excerpt }}</p><a class="text-link" href="{{ route('chronicles.show', $article->slug) }}">Read more</a></div></article>@empty<p>No articles are published yet.</p>@endforelse</div></div></section>
@endforeach
@include('site.partials.cta', ['eyebrow' => 'Plan your visit', 'heading' => 'Your healing journey can begin with a simple conversation.'])
@endsection
