@extends('layouts.site')
@section('title', $type === 'blog' ? 'Blogs' : 'News & Events')
@section('description', $type === 'blog' ? 'Ideas and practical applications for conscious relating, authentic connection, and everyday wellbeing.' : 'Retreats, healing programs, community gatherings, and seasonal moments at Takshasheela.')
@section('content')
@include('site.partials.hero', ['eyebrow' => 'Takshasheela chronicles', 'heading' => $type === 'blog' ? 'Staying Inspired & Connected' : 'News & Events', 'copy' => $type === 'blog' ? 'Ideas and practical applications for conscious relating, authentic connection, and a robust sense of self in everyday life.' : 'Stay connected with retreats, healing programs, community gatherings, and seasonal moments unfolding at Takshasheela.', 'variant' => $type === 'blog' ? 'hero--water' : 'hero--about'])
@if($featured)<section class="section"><div class="shell"><article class="journal-feature"><a href="{{ route('chronicles.show', $featured->slug) }}"><img src="{{ $featured->imageUrl() }}" alt="{{ $featured->image_alt }}" loading="lazy"></a><div class="journal-feature__copy"><p class="eyebrow">{{ $featured->category }}</p><h2>{{ $featured->title }}</h2><p>{{ $featured->excerpt }}</p><a class="text-link" href="{{ route('chronicles.show', $featured->slug) }}">{{ $type === 'blog' ? 'Read featured reflection' : 'Read update' }}</a></div></article></div></section>@endif
<section class="section section--cream" id="articles"><div class="shell"><div class="section-heading"><p class="eyebrow">{{ $type === 'blog' ? 'More from the journal' : 'Latest updates' }}</p><h2>{{ $type === 'blog' ? 'Stories of awareness and transformation.' : 'Stay connected with our latest news and events.' }}</h2></div><div class="card-grid">@forelse($articles->where('id', '!=', $featured?->id) as $article)<article class="feature-card"><a href="{{ route('chronicles.show', $article->slug) }}"><img src="{{ $article->imageUrl() }}" alt="{{ $article->image_alt }}" loading="lazy"></a><div class="feature-card__body"><p class="eyebrow">{{ $article->category }}</p><h3><a class="card-title-link" href="{{ route('chronicles.show', $article->slug) }}">{{ $article->title }}</a></h3><p>{{ $article->excerpt }}</p><a class="text-link" href="{{ route('chronicles.show', $article->slug) }}">Read more</a></div></article>@empty @if(!$featured)<p>No {{ $type === 'blog' ? 'blog articles' : 'news or events' }} are published yet.</p>@endif @endforelse</div></div></section>
@include('site.partials.cta', ['eyebrow' => $type === 'blog' ? 'Experience it for yourself' : 'Stay connected', 'heading' => $type === 'blog' ? 'Explore how these ideas come alive during a Takshasheela retreat.' : 'Contact us for upcoming retreat dates and community gatherings.'])
@endsection
