@extends('layouts.admin')
@php
    $editing = $offering->exists;
    $highlights = old('highlights_text', implode("\n", $offering->highlights ?? []));
    $includes = old('includes_text', implode("\n", $offering->includes ?? []));
    $itinerary = old('itinerary_text', collect($offering->itinerary ?? [])->map(fn ($step) => $step['time'].' | '.$step['title'].' | '.$step['description'])->implode("\n"));
@endphp
@section('title', $editing ? 'Edit '.$offering->name : 'Add wellness program')
@section('content')
<div class="page-heading"><div><p class="eyebrow">WELLNESS PROGRAM</p><h1>{{ $editing ? 'Edit '.$offering->name : 'Add offering' }}</h1><p class="muted">Creates the final item beneath a category and subcategory, with a listing card and detail page.</p></div><a class="button button-outline" href="{{ route('admin.wellness-offerings.index') }}">← All programs</a></div>
@if($subcategories->isEmpty())<section class="panel empty-state"><span class="empty-icon">◇</span><h3>Create a subcategory first</h3><p>Every offering must belong to a subcategory.</p><a class="button" href="{{ route('admin.wellness-subcategories.create') }}">Add subcategory</a></section>@else
<form method="post" action="{{ $editing ? route('admin.wellness-offerings.update', $offering) : route('admin.wellness-offerings.store') }}" enctype="multipart/form-data" class="stack about-editor">@csrf @if($editing) @method('PUT') @endif
<section class="panel form-panel"><div><p class="eyebrow">HIERARCHY &amp; LISTING</p><h2>Offering introduction</h2></div><label>Parent subcategory<select name="wellness_subcategory_id" required>@foreach($subcategories->groupBy('wellness_category_id') as $group)<optgroup label="{{ $group->first()->category->name }}">@foreach($group as $subcategory)<option value="{{ $subcategory->id }}" @selected((int) old('wellness_subcategory_id', $offering->wellness_subcategory_id) === $subcategory->id)>{{ $subcategory->name }}</option>@endforeach</optgroup>@endforeach</select><small>The top-level category is selected automatically from this subcategory. Moving across categories generates an available URL there.</small></label><label>Name<input name="name" value="{{ old('name', $offering->name) }}" maxlength="180" required><small>The URL slug is generated automatically when the program is created.</small></label><div class="form-columns"><label>Eyebrow / type<input name="eyebrow" value="{{ old('eyebrow', $offering->eyebrow) }}" maxlength="150" required></label><label>Duration<input name="duration" value="{{ old('duration', $offering->duration) }}" maxlength="100" placeholder="7 days or Tailored to assessment"></label></div><label>Short description<textarea name="short_description" rows="4" maxlength="1500" required>{{ old('short_description', $offering->short_description) }}</textarea></label><label>Listing highlights<textarea name="highlights_text" rows="5" maxlength="4000" required>{{ $highlights }}</textarea><small>Enter one highlight per line, up to 20.</small></label></section>
<section class="panel form-panel"><div><p class="eyebrow">IMAGE</p><h2>Program image</h2></div><div class="image-picker" data-image-picker><span class="image-picker-label">Listing and detail image</span><div class="image-picker-body"><img class="image-picker-preview" data-image-preview @if($offering->imageUrl()) src="{{ $offering->imageUrl() }}" @else hidden @endif alt="Current program image"><div class="image-picker-controls"><label>Choose image from device<input type="file" name="image" accept="image/jpeg,image/png,image/webp" data-image-input @required(!$editing)><small>JPG, PNG, or WebP. Maximum 2 MB and 6000 × 6000 pixels.</small></label><p class="image-picker-feedback muted" data-image-feedback aria-live="polite"></p></div></div></div><label>Image description<input name="image_alt" value="{{ old('image_alt', $offering->image_alt) }}" maxlength="255" required></label></section>
<section class="panel form-panel"><div><p class="eyebrow">DETAIL PAGE</p><h2>Program details</h2></div><label>Full description<textarea data-wysiwyg name="description" rows="7" maxlength="8000" required>{{ old('description', $offering->description) }}</textarea></label><label>What is included<textarea name="includes_text" rows="6" maxlength="5000" required>{{ $includes }}</textarea><small>Enter one item per line, up to 30.</small></label><label>Itinerary<textarea name="itinerary_text" rows="8" maxlength="12000" placeholder="First day | Consultation and preparation | Meet your practitioner and begin gentle preparation.">{{ $itinerary }}</textarea><small>Optional. Enter one step per line using: Time | Title | Description.</small></label><label>Who it may suit<textarea data-wysiwyg name="ideal_for" rows="5" maxlength="5000" required>{{ old('ideal_for', $offering->ideal_for) }}</textarea></label><div class="form-columns"><label>Final information heading<input name="secondary_title" value="{{ old('secondary_title', $offering->secondary_title) }}" maxlength="150" required placeholder="Your daily rhythm"></label><label>Display order<input type="number" name="sort_order" value="{{ old('sort_order', $offering->sort_order) }}" min="0" max="9999" required><small>Lower numbers appear first.</small></label></div><label>Final information text<textarea data-wysiwyg name="secondary_content" rows="5" maxlength="5000" required>{{ old('secondary_content', $offering->secondary_content) }}</textarea></label><label>Important note<textarea data-wysiwyg name="notice" rows="3" maxlength="2000">{{ old('notice', $offering->notice) }}</textarea></label></section>
<section class="panel form-panel"><div><p class="eyebrow">VISIBILITY</p><h2>Publishing</h2></div><label class="checkbox accommodation-publish"><input type="hidden" name="is_published" value="0"><input type="checkbox" name="is_published" value="1" @checked(old('is_published', $offering->is_published))> Published in navigation, listing, and detail pages</label></section>
<div class="about-save-bar"><p class="muted">Published offerings appear below their subcategory in the Wellness Programs dropdown.</p><div class="about-save-actions"><a class="button button-outline" href="{{ route('admin.wellness-offerings.index') }}">Cancel</a><button class="button" type="submit">{{ $editing ? 'Save offering' : 'Create offering' }} →</button></div></div>
</form>@endif
@endsection
