@extends('layouts.admin')
@php($editing = $category->exists)
@section('title', $editing ? 'Edit '.$category->name : 'Add wellness category')
@section('content')
<div class="page-heading"><div><p class="eyebrow">WELLNESS CATEGORY</p><h1>{{ $editing ? 'Edit '.$category->name : 'Add category' }}</h1><p class="muted">Controls a top-level dropdown category and its public listing page.</p></div><a class="button button-outline" href="{{ route('admin.wellness-categories.index') }}">← All categories</a></div>
<form method="post" action="{{ $editing ? route('admin.wellness-categories.update', $category) : route('admin.wellness-categories.store') }}" enctype="multipart/form-data" class="stack about-editor">@csrf @if($editing) @method('PUT') @endif
<section class="panel form-panel"><div><p class="eyebrow">MENU</p><h2>Category identity</h2><p class="muted">The name and description appear in the Wellness Programs dropdown.</p></div><label>Category name<input name="name" value="{{ old('name', $category->name) }}" maxlength="120" required><small>The URL slug is generated automatically when the category is created.</small></label><label>Menu description<input name="nav_description" value="{{ old('nav_description', $category->nav_description) }}" maxlength="255" required placeholder="Immersive retreat programs"></label></section>
<section class="panel form-panel"><div><p class="eyebrow">HERO</p><h2>Listing page introduction</h2></div><div class="form-columns"><label>Hero eyebrow<input name="hero_eyebrow" value="{{ old('hero_eyebrow', $category->hero_eyebrow) }}" maxlength="150" required></label><label>Hero heading<input name="hero_title" value="{{ old('hero_title', $category->hero_title) }}" maxlength="255" required></label></div><label>Hero description<textarea data-wysiwyg name="hero_description" rows="4" maxlength="2000" required>{{ old('hero_description', $category->hero_description) }}</textarea></label><div class="image-picker" data-image-picker><span class="image-picker-label">Hero image</span><div class="image-picker-body"><img class="image-picker-preview" data-image-preview @if($category->heroImageUrl()) src="{{ $category->heroImageUrl() }}" @else hidden @endif alt="Current category hero image"><div class="image-picker-controls"><label>Choose image from device<input type="file" name="image" accept="image/jpeg,image/png,image/webp" data-image-input @required(!$editing)><small>JPG, PNG, or WebP. Maximum 2 MB and 6000 × 6000 pixels.</small></label><p class="image-picker-feedback muted" data-image-feedback aria-live="polite"></p></div></div></div><label>Hero image description<input name="hero_image_alt" value="{{ old('hero_image_alt', $category->hero_image_alt) }}" maxlength="255" required></label></section>
<section class="panel form-panel"><div><p class="eyebrow">OFFERING LIST</p><h2>Grouped offering section</h2></div><div class="form-columns"><label>Section eyebrow<input name="section_eyebrow" value="{{ old('section_eyebrow', $category->section_eyebrow) }}" maxlength="150" required></label><label>Section heading<input name="section_title" value="{{ old('section_title', $category->section_title) }}" maxlength="255" required></label></div></section>
<section class="panel form-panel"><div><p class="eyebrow">INFORMATION BAND</p><h2>Optional supporting information</h2><p class="muted">Leave these fields empty to hide the dark information band.</p></div><div class="form-columns"><label>Eyebrow<input name="information_eyebrow" value="{{ old('information_eyebrow', $category->information_eyebrow) }}" maxlength="150"></label><label>Heading<input name="information_title" value="{{ old('information_title', $category->information_title) }}" maxlength="255"></label></div><label>Information body<textarea data-wysiwyg name="information_body" rows="5" maxlength="4000">{{ old('information_body', $category->information_body) }}</textarea><small>Use the toolbar to format this content.</small></label></section>
<section class="panel form-panel"><div><p class="eyebrow">CALL TO ACTION</p><h2>Closing invitation</h2></div><div class="form-columns"><label>Eyebrow<input name="cta_eyebrow" value="{{ old('cta_eyebrow', $category->cta_eyebrow) }}" maxlength="150" required></label><label>Heading<input name="cta_title" value="{{ old('cta_title', $category->cta_title) }}" maxlength="255" required></label></div><label>Supporting text<textarea data-wysiwyg name="cta_body" rows="3" maxlength="2000">{{ old('cta_body', $category->cta_body) }}</textarea></label></section>
<section class="panel form-panel"><div><p class="eyebrow">VISIBILITY</p><h2>Publishing and order</h2></div><div class="form-columns"><label>Display order<input type="number" name="sort_order" value="{{ old('sort_order', $category->sort_order) }}" min="0" max="9999" required><small>Lower numbers appear first in the dropdown.</small></label><label class="checkbox accommodation-publish"><input type="hidden" name="is_published" value="0"><input type="checkbox" name="is_published" value="1" @checked(old('is_published', $category->is_published))> Published on the website</label></div></section>
<div class="about-save-bar"><p class="muted">Saving updates the Wellness Programs dropdown and category listing page.</p><div class="about-save-actions"><a class="button button-outline" href="{{ route('admin.wellness-categories.index') }}">Cancel</a><button class="button" type="submit">{{ $editing ? 'Save category' : 'Create category' }} →</button></div></div>
</form>
@endsection
