@extends('layouts.admin')
@section('title', 'Wellness categories')
@section('content')
<div class="page-heading"><div><p class="eyebrow">WELLNESS PROGRAMS</p><h1>Categories</h1><p class="muted">Categories form the first level of the website dropdown, such as Packages, Services, and Training.</p></div><a class="button" href="{{ route('admin.wellness-categories.create') }}">Add category →</a></div>
<section class="panel"><div class="panel-heading"><div><h2>Wellness categories</h2><p class="muted">{{ $categories->count() }} {{ Str::plural('category', $categories->count()) }}</p></div><a href="{{ route('admin.wellness-subcategories.index') }}">Manage subcategories →</a></div>
@if($categories->isEmpty())<div class="empty-state"><span class="empty-icon">◇</span><h3>No wellness categories yet</h3><p>Add the first category, then create subcategories beneath it.</p><a class="button" href="{{ route('admin.wellness-categories.create') }}">Add category</a></div>@else
<div class="table-wrap"><table><thead><tr><th>Category</th><th>Subcategories</th><th>Offerings</th><th>Status</th><th>Order</th><th>Actions</th></tr></thead><tbody>@foreach($categories as $category)<tr><td><span class="table-title">{{ $category->name }}</span><small>/{{ $category->slug }} · {{ $category->nav_description }}</small></td><td>{{ $category->subcategories_count }}</td><td>{{ $category->offerings_count }}</td><td><span class="badge {{ $category->is_published ? 'badge-published' : 'badge-draft' }}">{{ $category->is_published ? 'Published' : 'Draft' }}</span></td><td>{{ $category->sort_order }}</td><td><div class="table-actions">@if($category->is_published)<a href="{{ $category->publicUrl() }}" target="_blank" rel="noopener">View ↗</a>@endif<a href="{{ route('admin.wellness-subcategories.index', ['category' => $category->id]) }}">Subcategories</a><a href="{{ route('admin.wellness-offerings.index', ['category' => $category->id]) }}">Offerings</a><a href="{{ route('admin.wellness-categories.edit', $category) }}">Edit</a><form method="post" action="{{ route('admin.wellness-categories.destroy', $category) }}" onsubmit="return confirm('Delete this empty category?')">@csrf @method('DELETE')<button class="text-danger" type="submit">Delete</button></form></div></td></tr>@endforeach</tbody></table></div>
@endif</section>
@endsection
